=== iesgrancapitan-llmm/mi-primera-pagina-web-josemmp2005/U4/dtd/dtd_externo.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellido, ciclo, (nota_final | nota_media))>
<!ATTLIST alumno
          expediente CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT nota_final (#PCDATA)>
<!ELEMENT nota_media (#PCDATA)>

=== iesgrancapitan-llmm/mi-primera-pagina-web-josemmp2005/U5/dtd/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "file:/C:/Users/Usuario/Desktop/dtd_externo.dtd">
<alumnos>
  <alumno expediente ="A001">
    <nombre>Jose M</nombre>
    <apellido>Mayen</apellido>
    <ciclo>DAW</ciclo>
    <nota_final>10</nota_final>  
  </alumno>
  <alumno>  
    <nombre>Pepe</nombre>
    <apellido>Perez</apellido>
    <ciclo>ASIR</ciclo>
    <nota_media>8</nota_media>  
  </alumno>
</alumnos>
