=== iesgrancapitan-llmm/mi-primera-pagina-web-josemmp2005/U5/UD5A3/ejercicio7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="persona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="persona">
    <xs:complexType>
      <xs:all>
        <xs:element ref="datos"/>
        <xs:element name="comentario" type="xs:string"/>
        <xs:element ref="formapago"/>
      </xs:all>
      <xs:attribute name="fecha_nacimiento" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datos">
    <xs:complexType>
      <xs:all>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="dni" type="xs:string"/>
        <xs:element name="nota" type="notaTipo"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="formapago">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numero" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="metodo" type="metodoTipo" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="metodoTipo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="tarjeta"/>
      <xs:enumeration value="transferencia"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="notaTipo">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== iesgrancapitan-llmm/mi-primera-pagina-web-josemmp2005/U5/UD5A3/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio7.xsd">
    <persona fecha_nacimiento="2005-02-12">
        <datos>
            <nombre>Jose</nombre>
            <apellidos>Mayen</apellidos>
            <dni>21023811H</dni>
            <nota>7.7</nota>
        </datos>
        <comentario>Estudiante 1ºDAW</comentario>
        <formapago metodo="tarjeta">
            <numero>1123123213123</numero>
        </formapago>
    </persona>
    <persona fecha_nacimiento="2004-02-12">
        <datos>
            <apellidos>Garcia</apellidos>
            <nota>10</nota>
            <dni>3129011H</dni>
            <nombre>Juan</nombre>
        </datos>
        <comentario>Estudiante 2ºDAW</comentario>
        <formapago metodo="transferencia">
            <numero>3621987337126</numero>
        </formapago>
    </persona>
</personas>
