=== iesgrancapitan-llmm/mi-primera-pagina-web-josemmp2005/U5/UD5A3/ejercicio6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="datos">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos" type="xs:string"/>
                                        <xs:element name="dni" type="xs:string"/>                                                       
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comentario" type="xs:string"/>
                            <xs:element name="formapago">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numero" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="metodo" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="fecha_nacimiento" type="xs:date"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== iesgrancapitan-llmm/mi-primera-pagina-web-josemmp2005/U5/UD5A3/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio6.xsd">
    <persona fecha_nacimiento="2005-02-12">
        <datos>
            <apellidos>Mayen</apellidos>
            <dni>21023811H</dni>
            <nombre>Jose</nombre>
        </datos>
        <comentario>Estudiante 1ºDAW</comentario>
        <formapago metodo="tarjeta">
            <numero>1123123213123</numero>
        </formapago>
    </persona>
    <persona fecha_nacimiento="2004-02-12">
        <datos>
            <nombre>Juan</nombre>
            <apellidos>Garcia</apellidos>
            <dni>3129011H</dni>
        </datos>
        <comentario>Estudiante 2ºDAW</comentario>
        <formapago metodo="transferencia">
            <numero>3621987337126</numero>
        </formapago>
    </persona>
</personas>
