<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
    <!ELEMENT contabilidad (apunte)*> <!-- <!ELEMENT contabilidad ((ingreso | gasto)*)> -->
    <!ELEMENT apunte ((ingreso | gasto)*, fecha, cantidad, concepto)> <!-- Añadimos el elemento apunte-->
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT ingreso (#PCDATA)> <!-- Añadimos elemento ingreso-->
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT concepto (#PCDATA)>
    <!ELEMENT gasto (#PCDATA)> <!-- Añadimos el elemento gasto-->
]>

<contabilidad>
    <apunte>
        <ingreso />
        <fecha>24 de febrero de 2011</fecha>
        <cantidad>1800,00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha>28 de febrero de 2011</fecha>
        <cantidad>74,25 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad>

<!--<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
    <!ELEMENT contabilidad ((ingreso | gasto)*)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT concepto (#PCDATA)>
]>
<contabilidad>
    <apunte>
        <ingreso />
        <fecha>24 de febrero de 2011</fecha>
        <cantidad>1800,00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha>28 de febrero de 2011</fecha>
        <cantidad>74,25 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad> -->