<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Factura [
    <!ELEMENT Factura (cabecera, apunte+)>
    <!ELEMENT cabecera (fecha, cliente)>    
    <!ATTLIST cabecera
            factura_id NMTOKEN #REQUIRED>
    <!ELEMENT fecha (mes | dia | anno)*>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT anno (#PCDATA)>
    <!ELEMENT cliente (direccion)>
    <!ATTLIST cliente
            cliente_id ID #REQUIRED
            nombre CDATA #IMPLIED
            telefono CDATA #IMPLIED>
    <!ELEMENT direccion (nombre_via, numero, localidad, provincia, cp, pais)>
    <!ELEMENT nombre_via (#PCDATA)>
    <!ATTLIST nombre_via
            tipo_via CDATA "Calle">
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT localidad (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT cp (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT apunte (concepto)>
    <!ATTLIST apunte
            descuento (promocion | regular) "regular"
            moneda CDATA  #FIXED "euro"
            precio CDATA #IMPLIED>
    <!ELEMENT concepto (#PCDATA)>
    <!ATTLIST concepto
            cantidad CDATA #IMPLIED>
]>


<Factura>
    <cabecera factura_id="12345">
        <fecha>
            <mes>Marzo</mes>
            <dia>15</dia>
            <anno>2021</anno>
        </fecha>
        <cliente cliente_id="J123" nombre="Juan García Sánchez" telefono="957-000-111">
            <direccion>
                <nombre_via >Fragua</nombre_via>
                <numero>6</numero>
                <localidad>Fernán Núñez</localidad>
                <provincia>Córdoba</provincia>
                <cp>14550</cp>
                <pais>España</pais>
            </direccion>
        </cliente>
    </cabecera>
    <apunte descuento="promocion" precio="57">
        <concepto cantidad="2">Tarjeta gráfica 3D</concepto>
    </apunte>
    <apunte moneda="euro" precio="27,5">
        <concepto>Memoria Flash</concepto>
    </apunte>
</Factura>
