<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
    <!ELEMENT paises (pais*)> <!--Añadimos el elementos paises-->
    <!ELEMENT pais (nombre | unionEuropea | otan)*> <!-- <!ELEMENT pais (nombre, unionEuropea, otan)> -->
    <!ELEMENT nombre (#PCDATA)> <!-- cambiamos EMPTY por PCDATA-->
    <!ELEMENT unionEuropea EMPTY>
    <!ELEMENT otan EMPTY>
]>
<paises>
    <pais>
        <nombre>España</nombre>
        <unionEuropea />
        <otan />
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan />
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais>
</paises>


<!--<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
    <!ELEMENT pais (nombre, unionEuropea, otan)>
    <!ELEMENT nombre EMPTY>
    <!ELEMENT unionEuropea EMPTY>
    <!ELEMENT otan EMPTY>
]>
<paises>
    <pais>
        <nombre>España</nombre>
        <unionEuropea />
        <otan />
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan />
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais>
</paises>-->
